/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FanBadge__factory } from "./FanBadge__factory";
export { FanRegistry__factory } from "./FanRegistry__factory";
