/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FanBadgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CORRECT_PREDICTION"
      | "COUNTRY_CONTRIBUTOR"
      | "EXPERT"
      | "FAN_BADGE"
      | "FIRST_CHECKIN"
      | "ROOKIE"
      | "STREAK_3"
      | "STREAK_7"
      | "TOP_FAN"
      | "badgesOf"
      | "balanceOf"
      | "hasMinted"
      | "mintBadge"
      | "minter"
      | "owner"
      | "safeBatchTransferFrom"
      | "safeTransferFrom"
      | "setMinter"
      | "setUri"
      | "transferOwnership"
      | "uri"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BadgeMinted" | "TransferSingle"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CORRECT_PREDICTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COUNTRY_CONTRIBUTOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "EXPERT", values?: undefined): string;
  encodeFunctionData(functionFragment: "FAN_BADGE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "FIRST_CHECKIN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ROOKIE", values?: undefined): string;
  encodeFunctionData(functionFragment: "STREAK_3", values?: undefined): string;
  encodeFunctionData(functionFragment: "STREAK_7", values?: undefined): string;
  encodeFunctionData(functionFragment: "TOP_FAN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "badgesOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasMinted",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBadge",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "minter", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "safeBatchTransferFrom",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUri",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "uri", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "CORRECT_PREDICTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COUNTRY_CONTRIBUTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "EXPERT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FAN_BADGE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "FIRST_CHECKIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ROOKIE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "STREAK_3", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "STREAK_7", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TOP_FAN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "badgesOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasMinted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintBadge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeBatchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMinter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUri", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;
}

export namespace BadgeMintedEvent {
  export type InputTuple = [
    to: AddressLike,
    tokenId: BigNumberish,
    badgeType: string
  ];
  export type OutputTuple = [to: string, tokenId: bigint, badgeType: string];
  export interface OutputObject {
    to: string;
    tokenId: bigint;
    badgeType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferSingleEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    id: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    id: bigint,
    value: bigint
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    id: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FanBadge extends BaseContract {
  connect(runner?: ContractRunner | null): FanBadge;
  waitForDeployment(): Promise<this>;

  interface: FanBadgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CORRECT_PREDICTION: TypedContractMethod<[], [bigint], "view">;

  COUNTRY_CONTRIBUTOR: TypedContractMethod<[], [bigint], "view">;

  EXPERT: TypedContractMethod<[], [bigint], "view">;

  FAN_BADGE: TypedContractMethod<[], [bigint], "view">;

  FIRST_CHECKIN: TypedContractMethod<[], [bigint], "view">;

  ROOKIE: TypedContractMethod<[], [bigint], "view">;

  STREAK_3: TypedContractMethod<[], [bigint], "view">;

  STREAK_7: TypedContractMethod<[], [bigint], "view">;

  TOP_FAN: TypedContractMethod<[], [bigint], "view">;

  badgesOf: TypedContractMethod<
    [fan: AddressLike],
    [[bigint[], bigint[]] & { tokenIds: bigint[]; amounts: bigint[] }],
    "view"
  >;

  balanceOf: TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;

  hasMinted: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  mintBadge: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish, badgeType: string],
    [void],
    "nonpayable"
  >;

  minter: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  safeBatchTransferFrom: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [void],
    "view"
  >;

  safeTransferFrom: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [void],
    "view"
  >;

  setMinter: TypedContractMethod<
    [newMinter: AddressLike],
    [void],
    "nonpayable"
  >;

  setUri: TypedContractMethod<
    [tokenId: BigNumberish, newUri: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uri: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CORRECT_PREDICTION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COUNTRY_CONTRIBUTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EXPERT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FAN_BADGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FIRST_CHECKIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROOKIE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STREAK_3"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STREAK_7"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOP_FAN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "badgesOf"
  ): TypedContractMethod<
    [fan: AddressLike],
    [[bigint[], bigint[]] & { tokenIds: bigint[]; amounts: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasMinted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintBadge"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish, badgeType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "minter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "safeBatchTransferFrom"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "setMinter"
  ): TypedContractMethod<[newMinter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUri"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newUri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uri"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getEvent(
    key: "BadgeMinted"
  ): TypedContractEvent<
    BadgeMintedEvent.InputTuple,
    BadgeMintedEvent.OutputTuple,
    BadgeMintedEvent.OutputObject
  >;
  getEvent(
    key: "TransferSingle"
  ): TypedContractEvent<
    TransferSingleEvent.InputTuple,
    TransferSingleEvent.OutputTuple,
    TransferSingleEvent.OutputObject
  >;

  filters: {
    "BadgeMinted(address,uint256,string)": TypedContractEvent<
      BadgeMintedEvent.InputTuple,
      BadgeMintedEvent.OutputTuple,
      BadgeMintedEvent.OutputObject
    >;
    BadgeMinted: TypedContractEvent<
      BadgeMintedEvent.InputTuple,
      BadgeMintedEvent.OutputTuple,
      BadgeMintedEvent.OutputObject
    >;

    "TransferSingle(address,address,address,uint256,uint256)": TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;
    TransferSingle: TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;
  };
}
