/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace FanRegistry {
  export type FanProfileStruct = {
    countryCode: string;
    totalPoints: BigNumberish;
    checkInStreak: BigNumberish;
    longestStreak: BigNumberish;
    lastFixtureId: BigNumberish;
    registered: boolean;
  };

  export type FanProfileStructOutput = [
    countryCode: string,
    totalPoints: bigint,
    checkInStreak: bigint,
    longestStreak: bigint,
    lastFixtureId: bigint,
    registered: boolean
  ] & {
    countryCode: string;
    totalPoints: bigint;
    checkInStreak: bigint;
    longestStreak: bigint;
    lastFixtureId: bigint;
    registered: boolean;
  };
}

export interface FanRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHECKIN_POINTS"
      | "awardPoints"
      | "checkIn"
      | "countryFanCount"
      | "countryPoints"
      | "getProfile"
      | "hasCheckedIn"
      | "isRegistered"
      | "owner"
      | "profiles"
      | "registerFan"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CheckedIn" | "FanRegistered" | "PointsAwarded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CHECKIN_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "awardPoints",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "countryFanCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "countryPoints",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCheckedIn",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "registerFan", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CHECKIN_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "awardPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checkIn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "countryFanCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "countryPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasCheckedIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerFan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CheckedInEvent {
  export type InputTuple = [
    fan: AddressLike,
    fixtureId: BigNumberish,
    pointsEarned: BigNumberish,
    newStreak: BigNumberish
  ];
  export type OutputTuple = [
    fan: string,
    fixtureId: bigint,
    pointsEarned: bigint,
    newStreak: bigint
  ];
  export interface OutputObject {
    fan: string;
    fixtureId: bigint;
    pointsEarned: bigint;
    newStreak: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FanRegisteredEvent {
  export type InputTuple = [fan: AddressLike, countryCode: string];
  export type OutputTuple = [fan: string, countryCode: string];
  export interface OutputObject {
    fan: string;
    countryCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsAwardedEvent {
  export type InputTuple = [
    fan: AddressLike,
    points: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [fan: string, points: bigint, reason: string];
  export interface OutputObject {
    fan: string;
    points: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FanRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FanRegistry;
  waitForDeployment(): Promise<this>;

  interface: FanRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHECKIN_POINTS: TypedContractMethod<[], [bigint], "view">;

  awardPoints: TypedContractMethod<
    [fan: AddressLike, points: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  checkIn: TypedContractMethod<[fixtureId: BigNumberish], [void], "nonpayable">;

  countryFanCount: TypedContractMethod<[arg0: string], [bigint], "view">;

  countryPoints: TypedContractMethod<[arg0: string], [bigint], "view">;

  getProfile: TypedContractMethod<
    [fan: AddressLike],
    [FanRegistry.FanProfileStructOutput],
    "view"
  >;

  hasCheckedIn: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  isRegistered: TypedContractMethod<[fan: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  profiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        countryCode: string;
        totalPoints: bigint;
        checkInStreak: bigint;
        longestStreak: bigint;
        lastFixtureId: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;

  registerFan: TypedContractMethod<[countryCode: string], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHECKIN_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "awardPoints"
  ): TypedContractMethod<
    [fan: AddressLike, points: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkIn"
  ): TypedContractMethod<[fixtureId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "countryFanCount"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "countryPoints"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<
    [fan: AddressLike],
    [FanRegistry.FanProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasCheckedIn"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[fan: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        countryCode: string;
        totalPoints: bigint;
        checkInStreak: bigint;
        longestStreak: bigint;
        lastFixtureId: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerFan"
  ): TypedContractMethod<[countryCode: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CheckedIn"
  ): TypedContractEvent<
    CheckedInEvent.InputTuple,
    CheckedInEvent.OutputTuple,
    CheckedInEvent.OutputObject
  >;
  getEvent(
    key: "FanRegistered"
  ): TypedContractEvent<
    FanRegisteredEvent.InputTuple,
    FanRegisteredEvent.OutputTuple,
    FanRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PointsAwarded"
  ): TypedContractEvent<
    PointsAwardedEvent.InputTuple,
    PointsAwardedEvent.OutputTuple,
    PointsAwardedEvent.OutputObject
  >;

  filters: {
    "CheckedIn(address,uint32,uint32,uint16)": TypedContractEvent<
      CheckedInEvent.InputTuple,
      CheckedInEvent.OutputTuple,
      CheckedInEvent.OutputObject
    >;
    CheckedIn: TypedContractEvent<
      CheckedInEvent.InputTuple,
      CheckedInEvent.OutputTuple,
      CheckedInEvent.OutputObject
    >;

    "FanRegistered(address,string)": TypedContractEvent<
      FanRegisteredEvent.InputTuple,
      FanRegisteredEvent.OutputTuple,
      FanRegisteredEvent.OutputObject
    >;
    FanRegistered: TypedContractEvent<
      FanRegisteredEvent.InputTuple,
      FanRegisteredEvent.OutputTuple,
      FanRegisteredEvent.OutputObject
    >;

    "PointsAwarded(address,uint32,string)": TypedContractEvent<
      PointsAwardedEvent.InputTuple,
      PointsAwardedEvent.OutputTuple,
      PointsAwardedEvent.OutputObject
    >;
    PointsAwarded: TypedContractEvent<
      PointsAwardedEvent.InputTuple,
      PointsAwardedEvent.OutputTuple,
      PointsAwardedEvent.OutputObject
    >;
  };
}
