/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FanBadge } from "./FanBadge";
export type { FanRegistry } from "./FanRegistry";
export * as factories from "./factories";
export { FanBadge__factory } from "./factories/FanBadge__factory";
export { FanRegistry__factory } from "./factories/FanRegistry__factory";
